title: Data for Good
description: La technologie au service de l'impact social
author: Data for Good
twitter:
  username: dataforgoodfr
facebook:
  publisher: dataforgoodfr
logo: /images/logo.png
social:
  links:
    - https://twitter.com/dataforgoodfr
    - https://www.facebook.com/dataforgoodfr
    - https://www.linkedin.com/company/10627994/
    - https://github.com/dataforgoodfr
google_site_verification: 5MDM_rNGP6gGksm9Lo8Yh_w8kjmP16VBypX1_Ev8MT4
lang: fr_FR

# Build settings
markdown: kramdown

collections:
  projects:
    output: true

number_of_season: 3

plugins:
  - jekyll-seo-tag
